name: Create cherrypick PR

on:
  pull_request:
      types:
        - closed
      branches:
        - 'dev'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains( github.event.pull_request.labels.*.name, 'cherrypick:5.3')
    runs-on: ubuntu-latest
    env:
      commit-hash: ${{ github.event.pull_request.head.sha }}
      pr-number: ${{ github.event.number }}
      stable-branch: '5.3'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Use the appropriate branch for the documentation version.
        ref: ${{ env.stable-branch }}

    - name: Create branch for cherrypick 
      run: |
        git checkout -b cherrypick-${{ env.pr-number }} ${{ env.stable-branch }}
        git cherry-pick -m 1 ${{ env.commit-hash }}

    - run: |
        echo The PR was merged and is a cherrypick for 5.3
  