name: Create cherrypick PR

on:
  pull_request:
      types:
        - closed
      branches:
        - 'dev'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains( github.event.pull_request.labels.*.name, 'cherrypick:5.3')
    runs-on: ubuntu-latest
    env:
      commit-hash: ${{ github.event.pull_request.head.sha }}
      pr-number: ${{ github.event.number }}
      stable-branch: '5.3'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Use the appropriate branch for the documentation version.
        ref: ${{ env.stable-branch }}

    - name: Create branch for cherrypick
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch
        git checkout -b cherrypick-${{ env.pr-number }} ${{ env.stable-branch }}

    - name: Cherrypick the commit
      id: actually_cherrypick
      continue-on-error: true
      run: |
        git cherry-pick -m 1 ${{ env.commit-hash }}

    - name: Failed
      if: steps.actually_cherrypick.outcome == 'failure'
      run: |
        echo Failed

    - name: Succeeded
      if: steps.actually_cherrypick.outcome == 'success'
      run: |
        echo Succeeded

  