name: Create Cherrypick PR

on:
  pull_request:
      types:
        - closed
      branches:
        # TODO extract this to an env variable?
        - 'dev'

env:
  # TODO add a way to handle multiple potential cherrypick targets.
  TARGET_BRANCH: '5.3'
  GHA_BOT_USERNAME: 'github-actions[bot]'
  GHA_BOT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'

jobs:
  Create-cherrypick-PR:
    # Only attempt to cherrypick PRs with a single commit. 
    # PRs with multiple commits are merged with "Squash and merge" and are structured differently.
    # The cherrypick label is hardcoded because contains() doesn't seem to be able to use an environment variable as a second argument.
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.commits == 1 && contains( github.event.pull_request.labels.*.name, 'cherrypick:5.3' ) }}
    runs-on: ubuntu-latest
    env:
      # In the typical case of a PR with a single commit, merged with a merge commit,
      # this will be the commit to cherrypick.
      COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}

    steps:
  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ env.TARGET_BRANCH }}

    - name: Cherrypick Commit
      id: cherrypick_commit
      continue-on-error: true
      # The GitHub Actions bot credentials are required here to be able to cherrypick.
      # TODO maybe only fetch some branches?
      run: |
        git config user.name "${{ env.GHA_BOT_USERNAME }}"
        git config user.email "${{ env.GHA_BOT_EMAIL }}"
        git fetch
        git cherry-pick -m 1 ${{ env.COMMIT_HASH }}

    - name: Create Pull Request
      if: steps.cherrypick_commit.outcome == 'success'
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: 'Cherrypick to ${{ env.TARGET_BRANCH }}'
        branch: 'cherrypick-${{ env.PR_NUMBER }}-${{ env.TARGET_BRANCH }}'
        delete-branch: true

        # Configure the commit author.
        author: 'Godot Organization <noreply@godotengine.org>'
        committer: 'Godot Organization <noreply@godotengine.org>'

        # Configure the pull request.
        title: 'Cherrypick ${{ env.PR_NUMBER }} to ${{ env.TARGET_BRANCH }}'
        body: 'Cherrypick #${{ env.PR_NUMBER }} to ${{ env.TARGET_BRANCH }}.'
        # TODO only add the bug or enhancement label, depending on which the original PR uses.
        labels: 'bug,enhancement'

    - name: Handle failure
      if: steps.cherrypick_commit.outcome == 'failure'
      run: |
        echo "Can't automatically cherrypick. Potential causes:"
        echo "- PR has multiple commits. Did you squash and merge?"
        echo "- Cherrypick did not apply cleanly and can't be auto-merged."
